language: node_js
node_js:
  - '0.10'
  - '0.11'
services:
  - mongodb
before_script:
  - sleep 15
  - npm install -g bower
  - bower install
  - NODE_ENV='test' ./node_modules/.bin/knex migrate:latest
matrix:
  allow_failures:
    - node_js: '0.11'